# SPDX-License-Identifier: Apache-2.0
# Eclipse Mosquitto 2.x config — anonymous bind on the WireGuard mesh
# only. For bound on public IP, switch to per-edge credentials.

listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice