# SPDX-License-Identifier: Apache-2.0
"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-28

Creates the six base tables:
- tenants (with slug for subdomain routing)
- users (admin / member / viewer, scoped per tenant)
- nodes (GPU edge nodes registered by edge-agent)
- cameras (per-tenant, with mtx_path)
- events (detection history)
- alert_rules (Phase 2 surface, schema present so future migrations are stable)

NOTE: this migration is hand-written, not autogenerated, because the
seed data shape is well-known. Subsequent migrations may use
`alembic revision --autogenerate -m "..."` once the schema stabilises.
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("slug", sa.String(63), nullable=False, unique=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("subdomain", sa.String(63), nullable=False, unique=True),
        sa.Column("branding", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Integer(),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False, server_default="admin"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
        sa.CheckConstraint(
            "role IN ('admin', 'member', 'viewer')", name="ck_users_role"
        ),
    )
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])

    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Integer(),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("hostname", sa.String(255), nullable=False, unique=True),
        sa.Column("tailscale_ip", sa.String(45), nullable=False),
        sa.Column("gpu_model", sa.String(100), nullable=True),
        sa.Column("max_cameras", sa.Integer(), nullable=False, server_default="50"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "current_config_version",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_nodes_tenant_id", "nodes", ["tenant_id"])

    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Integer(),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "node_id",
            sa.Integer(),
            sa.ForeignKey("nodes.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("location", sa.String(255), nullable=True),
        sa.Column("rtsp_url", sa.Text(), nullable=False),
        sa.Column("mtx_path", sa.String(63), nullable=False, unique=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("zones", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("object_filters", sa.Text(), nullable=False, server_default="{}"),
        sa.Column(
            "recording_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "retention_days", sa.Integer(), nullable=False, server_default="7"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "mtx_path ~ '^[a-z0-9]+$'", name="ck_mtx_path_format"
        ),
    )
    op.create_index("ix_cameras_tenant_id", "cameras", ["tenant_id"])
    op.create_index("ix_cameras_node_id", "cameras", ["node_id"])

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("event_uuid", sa.String(63), nullable=False, unique=True),
        sa.Column("class_label", sa.String(40), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("bbox", sa.Text(), nullable=False),
        sa.Column("snapshot_url", sa.Text(), nullable=True),
        sa.Column("clip_url", sa.Text(), nullable=True),
        sa.Column(
            "clip_built", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_events_tenant_id", "events", ["tenant_id"])
    op.create_index("ix_events_camera_id", "events", ["camera_id"])
    op.create_index("ix_events_tenant_camera", "events", ["tenant_id", "camera_id"])

    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("class_filter", sa.String(40), nullable=True),
        sa.Column("notification_channels", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("schedule", sa.Text(), nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_alert_rules_tenant_id", "alert_rules", ["tenant_id"])


def downgrade() -> None:
    op.drop_index("ix_alert_rules_tenant_id", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index("ix_events_tenant_camera", table_name="events")
    op.drop_index("ix_events_camera_id", table_name="events")
    op.drop_index("ix_events_tenant_id", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_cameras_node_id", table_name="cameras")
    op.drop_index("ix_cameras_tenant_id", table_name="cameras")
    op.drop_table("cameras")
    op.drop_table("nodes")
    op.drop_index("ix_users_tenant_id", table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")